# El nombre del flujo de trabajo. 
name: Aprendiendo GitHub Actions 
# El nombre de las ejecuciones de flujo de trabajo generadas a partir del flujo de trabajo.
run-name: ¡Estoy aprendiendo GitHub Actions! 
#definir qué eventos pueden hacer que se ejecute el flujo de trabajo.
on: [push] 

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
       
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # - name: Verificar archivos
      #   run: ls -la

      - name: Correr script
        run: node .github/script/hola_mundo.js